image: ubuntu:16.04

stages:
  - test

variables:
  INSIDE_DOCKER: "yes"
  POSTGRES_DB: dbname # set database
  POSTGRES_USER: username # set username
  POSTGRES_PASSWORD: ""  

before_script:
  - apt-get update
  - apt-get -y upgrade
  - apt-get install openssh-client bind9-host -y

.test-check:
  script:
    - true

test-docker-exec:
  stage: test
  services:
    - registry.gitlab.com/postgres-ai-team/postgres-checkup:postgres11
      alias: replica1
  script:
    - ssh replica1 "echo hello from replica1 container"
    - echo "We not failed if you can see this"
