image: ubuntu:16.04

stages:
  - test

variables:
  INSIDE_DOCKER: "yes"
  POSTGRES_DB: dbname # set database
  POSTGRES_USER: username # set username
  POSTGRES_PASSWORD: ""  

before_script:
  - echo "export PATH=\$PATH:/usr/lib/go-1.9/bin" >> ~/.profile
  - source ~/.profile

.test-check:
  script:
    - docker exec -it postgres "ls" && echo "docker exec successfull"

test-docker-exec:
  stage: test
  script:
    - echo "We not failed if you can see this"
